# Generated by Django 4.2 on 2026-05-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_booking_id_alter_parkingslot_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
